### ISSUE TITLE
Revisit Harvester doc of v1.2.0 official release

### ISSUE THREAD

**Issue by guangbochen** [harvester/docs#373]
Please help to revisit the Harvester v1.2.0 version doc, we will need to check and update the following sections:
- update outdated content & images
- add new content for the v1.2.0 version
- improve the example and uses cases if possible
- may refer to https://github.com/harvester/docs/issues/337 as an example checklist

### Pages:
- [x] Harvester overview @guangbochen  - no changes needed
- [x] Installation @masteryyh
  - https://github.com/harvester/docs/pull/380 - PR review @guangbochen @vickyhella 
- [x] Air-gap env & Upgrade @starbops @bk201
  - https://github.com/harvester/docs/pull/381 
- [x] Authentication, Upload Images, Host Management @starbops
  - https://github.com/harvester/docs/pull/404
  - https://github.com/harvester/docs/pull/401
- [x] VM Management part 1 (from Create a VM to VM Backup, Snapshot & Restore) @WebberHuang1118 
  - https://github.com/harvester/docs/pull/387 - PR review @guangbochen @LucasSaintarbor 
- [x] VM Management part 2 (from Live migration to Clone VM) @Vicente-Cheng 
  - https://github.com/harvester/docs/pull/394
- [x] Volume Management @futuretea 
  - https://github.com/harvester/docs/pull/302
- [x] Networking @yaocw2020 
  - https://github.com/harvester/docs/pull/323
- [x] Logging & Monitoring @w13915984028 
  - https://github.com/harvester/docs/pull/384
- [x] Advanced @chrisho
  - https://github.com/harvester/docs/pull/386
- [x] Rancher Integration @guangbochen 
    - https://github.com/harvester/docs/pull/405
- [x] Harvester Terraform Provider @futuretea 
  - https://github.com/harvester/docs/pull/400
- [x] Troubleshooting @Vicente-Cheng 
  - https://github.com/harvester/docs/pull/395
- [x] FAQ - no changes required
- [x] Add v1.2 API doc @chrisho @vickyhella 
  - https://github.com/harvester/docs/pull/388

Note: prefer to have PR submitted before 08/11

**Comment by w13915984028** [comment]
Also add the `vcluster-rancher` ? cc @guangbochen

**Comment by w13915984028** [comment]
@ibrokethecloud 

The [PCI Devices](https://docs.harvesterhci.io/dev/advanced/pcidevices) is not `Experimental` in v1.2.0, I can update doc by removing the `Experimental`, but please check other parts, if some texts/pictures need to be updated as well, thanks.

**Comment by chrisho** [comment]
> @ibrokethecloud
> 
> The [PCI Devices](https://docs.harvesterhci.io/dev/advanced/pcidevices) is not `Experimental` in v1.2.0, I can update doc by removing the `Experimental`, but please check other parts, if some texts/pictures need to be updated as well, thanks.

I created a pr for the Advance document updated,  I can remove the `Experimental` base on it.

**Comment by guangbochen** [comment]
Close as all of the core PRs for v1.2.0 are merged; please help to track other doc enhancement separately via new GH issues.
